[MOS-686] Fixed MTP availability only after phone unlocked
mudita/usb_stack pull request #76
Opened 2023-05-09 12:41 UTC by rrandomsky

Fixed file access via MTP even when phone is not unlocked. Now access is granted when the phone is unlocked by the user entering a passcode. If the phone is not passcode protected (passcode is nor set) then access to the files is always possible via MTP.

_Related to PR in MuditaOS: https://github.com/mudita/MuditaOS/pull/4068_

2023-05-10 08:09 UTC, SP2FET commented
For me - it's not a fix, it's a pretty simple workaround. Instead of locking the initialization of the MTP, we should implement handling Access Denied response when the device shouldn't be available from PC
![image](https://github.com/mudita/usb_stack/assets/23299649/e08be347-ec90-4579-b6f3-4df4cc692edb)

2023-05-10 08:29 UTC, swichu91 requested changes
I'm sorry to say that, but this is not an acceptable solution. Bartek already sent you a snippet from the MTP specification which describes a possible solution to this problem. Please, get familiar with it. In any case, you can consult it with me or any other member of the MOS team :)

2023-05-11 14:50 UTC, rrandomsky commented
I took easy way, and it' works fine on Ubuntu. I'll ask someone to check it on Windows, after your approvals.

2023-05-15 08:56 UTC, SP2FET commented on mtp/mtp.c
> +        if (mtpApp->is_blocked) { log_debug("[MTP] security locked - MTP access denied"); }
```suggestion
        if (mtpApp->is_locked) { log_debug("[MTP] security locked - MTP access denied"); }
```

2023-05-15 08:56 UTC, SP2FET commented on mtp/mtp.h
> +    bool is_blocked;
```suggestion
    bool is_locked;
```

2023-05-18 09:26 UTC, swichu91 approved these changes

2023-05-18 13:43 UTC, merged